### ISSUE TITLE
ReactionRole is not a constructor

### ISSUE THREAD

**Issue by Whishoryi** [makigas/discordjs-reaction-role#7]
Hi.

I'm using [this package](https://npmjs.org/discordjs-reaction-role) to simplify role assignments in my Discord server. **However,** the code below:

```js
const ReactionRole = require("discordjs-reaction-role")
const ReactionClass = new ReactionRole(client, [
    {
        messageId: "835971474966708256", reaction: "📣", roleId: "835971067389542511",
        messageId: "835971474966708256", reaction: "📁", roleId: "835018389898264617"
    }
]);
```

Returns the following TypeError: `TypeError: ReactionRole is not a constructor`

Any and all help is appreciated. Unsure as to *why* the TypeError is being thrown.

**Comment by Whishoryi** [comment]
Realised I didn't attach `.default` to the require for discordjs-reaction-role. Though how do I get the bot to react to the specified messages?

**Comment by Whishoryi** [comment]
Guess I'm not getting help with this then. I joined the Discord server for "Makigas" and was banned or kicked.

**Comment by Whishoryi** [comment]
[This package](https://npmjs.org/discordjs-reaction-role) is undocumented. It only shows how to define & setup the `ReactionRole` class.

**Comment by danirod** [comment]
The bot starts reacting to the messages as soon as the constructor gets called, because it setups the required event listeners.

This is an ES Module package so you’re right in that you need to call `.default`, although you are encouraged to use `import ReactionRole from "discordjs-reaction-role"` instead.

You were banned because English is not allowed at our server. Plus we have some servers in common and looking up your username at their modlogs says you’ve been sending DM spam in the past.

**Comment by Whishoryi** [comment]
Then don't write a package under your organization that commonly speaks Spanish, whereas your package is coded in full English then get pissed that I spoke English.

**Comment by danirod** [comment]
Yeah, it is true that we should be less scared to write code in Spanish – it is a better language than English anyway with more native speakers. Too lazy to break the system, though.

I didn't get pissed, in fact, we usually don't ban natives because we don't expect them to pass the onboard process in any case, since the secret password to unlock the server is written inside the server rules. They usually leave by themselves after they get bored.

However, DM spam has become common in Discord recently and our community already receives enough of it. Seeing in the modlogs of servers we had in common that your user ID was already kicked in the past because of DM spam makes your account an instantaneous threat, thus a ban rather than a kick or just waiting.

Have a good day.

**Comment by Whishoryi** [comment]
Send screenshots of the logs, please. I'd like to file a dispute with them.

**Comment by danirod** [comment]
Sure. See, this is what I get in my modlog when I paste your user ID. These are the different stages your GuildMember has seen in the server I mod.

![09ED762C-4162-4234-B5B6-0B0EBA991EA9](https://user-images.githubusercontent.com/1568690/116818747-4574ce80-ab6d-11eb-818b-9f7e22b33f52.jpeg)

However, we used to have the Discord.js server in common, and this is what I see in their modlogs when I paste the same user ID. Despite the name being changed, the user ID stays the same no matter the changes to the tag.

![977F505E-2584-4CC6-9E62-641ED2A64374](https://user-images.githubusercontent.com/1568690/116818762-532a5400-ab6d-11eb-88a0-9d3bcf390628.jpeg)

There are additional messages including screenshots in the server, but I find unpolite to just subcopy stuff by other people in a GitHub issue. I bet you can rejoin and paste your user ID in the search box to see the context.

**Comment by Whishoryi** [comment]
Was unaware of these entries, thanks.

**Comment by Whishoryi** [comment]
Interestingly, now that I investigate the screenshots:
 - The first screenshot is from your server. The same day you banned me, with no legitimate reason.
 -  The second screenshot is from Discord.js support, where I got kicked when I accidentally sent a friend a invite where an image didn't upload to my file server.

Seems a bit discriminative, if you ask me. Also, I'm Hispanic, fyi, if you thought I didn't speak Spanish. Natively, no.
